// <auto-generated />
namespace Xco.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Baseline : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Baseline));
        
        string IMigrationMetadata.Id
        {
            get { return "201211042223143_Baseline"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
